const assert = require('assert')
const { load } = require('./load')
const a = load('agent/Agent.js')
const copy = v => JSON.parse(JSON.stringify(v))
const A = 'imap:ada@example.com', B = 'imap:bob@example.com'
const jobs = [
  { id:'r', messageId:'42:INBOX', accountId:A, state:'running', created:2 },
  { id:'b', messageIds:['42:INBOX','43:INBOX'], accountId:B, state:'done', created:3 },
  { id:'old', messageId:'42:INBOX', accountId:A, state:'done', created:1 }
]
assert.equal(a.jobFor(jobs,'42:INBOX',A).id,'r')
assert.equal(a.jobFor(jobs,'42:INBOX',B).id,'b')
assert.equal(a.jobFor(jobs,'42:INBOX',''),null)
assert.equal(a.jobFor(jobs,'43:INBOX',A),null)
assert.deepEqual(copy(a.jobsByMessage(jobs,B)),{'42:INBOX':jobs[1],'43:INBOX':jobs[1]})
assert.deepEqual(copy(a.attentionByMessage(jobs,[],A)),{})
assert.equal(a.wantsAttention({...jobs[0],resultReady:true},[]),true)
assert.equal(a.wantsAttention({...jobs[0],resultReady:true},['r']),false)
assert.deepEqual(copy(a.markSeen(['r'],'r')),['r'])
assert.equal(a.anyActive(jobs),true)
assert.equal(a.anyActive([]),false)
assert.equal(a.stateLabel({state:'running',resultReady:true}),'Ready')
assert.equal(a.detailText({state:'failed',error:'No terminal'}),'No terminal')
assert.deepEqual(copy(a.newlyFinished(jobs,[{...jobs[0],state:'done'}])).map(j=>j.id),['r'])
assert.deepEqual(copy(a.parseJobs('bad')),[])
assert.deepEqual(copy(a.parseShown('{"job":{"id":"r"},"output":"<b>plain</b>"}')),{job:{id:'r'},output:'<b>plain</b>'})
const summary = {id:'42:INBOX',subject:'Invoice',from:{email:'x@example.com'},to:[{email:'ada@example.com'}]}
const payload = JSON.parse(a.payload(summary,'日本語\n$() "quotes"', 'ada@example.com','INBOX','Summarize',A))
assert.equal(payload.accountId,A)
assert.equal(payload.messageId,'42:INBOX')
assert.ok(payload.message.includes('日本語\n$() "quotes"'))
assert.ok(!('command' in payload) && !('scope' in payload))
const selection = JSON.parse(a.selectionPayload([{...summary,bodyText:'Actual body'},{...summary,id:'43:INBOX',bodyText:'Another body'}],'ada@example.com','INBOX','Compare',A))
assert.ok(selection.messages[0].message.includes('Actual body'))
assert.ok(selection.messages[1].message.includes('Another body'))
assert.ok(!('command' in selection) && !('scope' in selection))
assert.equal(a.folderOf('42:Archive','inbox','imap'),'Archive')
assert.equal(a.folderOf('42:33','inbox','hey'),'inbox')
const fields = {to:'x@example.com',subject:'Plan',body:'Keep this',from:'alias@example.com',draftKey:'draft1'}
const draft = JSON.parse(a.draftPayload(fields,'Rewrite','ada@example.com',A))
assert.equal(draft.draft.from,fields.from)
assert.equal(draft.draftKey,'draft1')
assert.equal(draft.draftFingerprint,a.draftFingerprint(fields))
assert.notEqual(a.draftFingerprint({...fields,body:'Changed'}),draft.draftFingerprint)
assert.ok(!('command' in draft) && !('scope' in draft))
const drafts = [{id:'d1',kind:'draft',accountId:A,draftKey:'draft1',created:1},{id:'d2',kind:'draft',accountId:A,draftKey:'draft2',created:2},{id:'d3',kind:'draft',accountId:B,draftKey:'draft1',created:3}]
assert.deepEqual(copy(a.draftJobs(drafts,A,'draft1')).map(j=>j.id),['d1'])
assert.deepEqual(copy(a.draftJobs(drafts,A,'draft2')).map(j=>j.id),['d2'])
assert.deepEqual(copy(a.draftJobs(drafts,A,'')).map(j=>j.id),[])
assert.equal(a.draftAnswer({state:'running'},'Partial'),'')
assert.equal(a.draftAnswer({state:'running',resultReady:true},'Ready'),'Ready')
assert.equal(a.draftAnswer({state:'done',question:'Clarify?'},'Not a body'),'')
assert.equal(a.draftAnswer({state:'failed'},'Unusable'),'')
assert.ok(a.draftAsks().every(x=>x.label && x.prompt))
console.log('test_agent.js ok')

assert.equal(a.draftAnswer({state:'done'},'Full text\nQUESTION: ordinary mail text\n'),'Full text\nQUESTION: ordinary mail text\n')
assert.equal(a.selectionJob(jobs,['42:INBOX','43:INBOX'],A),null)
assert.equal(a.selectionJob(jobs,['43:INBOX','42:INBOX'],B).id,'b')
